"""Characterisation tests: pin what the pipeline does today, before anything changes.

For each seeded input case the unmodified pipeline is run once. Its output (or the exception
it raises) is saved as the golden record, and a pytest file is generated that re-runs the
pipeline and compares. Odd behaviour is pinned as it is; it is never fixed here.
"""

from __future__ import annotations

import json
import shutil
from dataclasses import dataclass, replace
from pathlib import Path

import pandas as pd

from datagen.generate import GenConfig, write
from teleguard.tracer import load_module

_CLEAN = GenConfig(null_user_rate=0.0, duplicate_rate=0.0, error_rate=0.0, slow_rate=0.0)

CASES: dict[str, GenConfig | None] = {
    "normal": GenConfig(seed=42),
    "single_event": replace(_CLEAN, seed=1, n_batches=1, events_per_batch=1),
    "heavy_nulls": GenConfig(seed=7, n_batches=2, events_per_batch=200, null_user_rate=0.5),
    "all_users_null": GenConfig(seed=8, n_batches=1, events_per_batch=50, null_user_rate=1.0),
    "heavy_duplicates": GenConfig(seed=9, n_batches=2, events_per_batch=200, duplicate_rate=0.5),
    "slow_loads": GenConfig(seed=10, n_batches=1, events_per_batch=200, slow_rate=0.3),
    "empty": None,  # one empty batch file
}

_TEST_TEMPLATE = '''"""Characterisation tests for {name}. GENERATED by teleguard.workflow; do not edit.

The golden files pin what the pipeline does today, including behaviour that looks wrong.
"""

import io
import json
from pathlib import Path

import pandas as pd
import pytest

from teleguard.tracer import load_module

ROOT = Path(__file__).resolve().parents[2]
LEGACY = ROOT / "pipelines" / "{name}" / "legacy" / "run.py"
DATA = ROOT / "tests" / "data" / "{name}"
GOLDEN = Path(__file__).parent / "golden" / "{name}"
CASES = sorted(p.stem for p in GOLDEN.glob("*.json"))


def _run(case: str) -> pd.DataFrame:
    return load_module(LEGACY).run(DATA / case)


def _roundtrip(df: pd.DataFrame) -> pd.DataFrame:
    return pd.read_csv(io.StringIO(df.to_csv(index=False)), keep_default_na=False)


@pytest.mark.parametrize("case", CASES)
def test_case_matches_golden(case: str) -> None:
    expected = json.loads((GOLDEN / f"{{case}}.json").read_text())
    if "raises" in expected:
        with pytest.raises(Exception) as info:
            _run(case)
        assert type(info.value).__name__ == expected["raises"]
        assert str(info.value) == expected["message"]
        return
    result = _run(case)
    assert list(result.columns) == expected["columns"]
    assert len(result) == expected["rows"]
    golden = pd.read_csv(GOLDEN / f"{{case}}.csv", keep_default_na=False)
    pd.testing.assert_frame_equal(_roundtrip(result), golden, check_exact=False, rtol=1e-9)


def test_golden_covers_every_case() -> None:
    assert len(CASES) >= {n_cases}
'''


@dataclass
class CaseOutcome:
    case: str
    rows: int | None
    raises: str | None
    message: str | None

    def describe(self) -> str:
        if self.raises:
            return f"`{self.case}`: the pipeline crashes with {self.raises}: {self.message}"
        return f"`{self.case}`: runs and produces {self.rows} output rows"


def _write_inputs(data_dir: Path) -> None:
    if data_dir.exists():
        shutil.rmtree(data_dir)
    for case, cfg in CASES.items():
        case_dir = data_dir / case
        if cfg is None:
            case_dir.mkdir(parents=True)
            (case_dir / "batch_0001.jsonl").write_text("")
        else:
            write(cfg, case_dir)


def build(pipeline_dir: Path, repo_root: Path) -> list[CaseOutcome]:
    """Generate inputs, record golden outputs, and write the pytest file. Returns outcomes."""
    name = pipeline_dir.name
    legacy_run = pipeline_dir / "legacy" / "run.py"
    data_dir = repo_root / "tests" / "data" / name
    golden_dir = repo_root / "tests" / "characterisation" / "golden" / name
    if golden_dir.exists():
        shutil.rmtree(golden_dir)
    golden_dir.mkdir(parents=True)
    _write_inputs(data_dir)

    outcomes = []
    for case in CASES:
        try:
            result = load_module(legacy_run).run(data_dir / case)
        except Exception as exc:  # noqa: BLE001 - a crash is behaviour worth pinning
            record = {"raises": type(exc).__name__, "message": str(exc)}
            (golden_dir / f"{case}.json").write_text(json.dumps(record, indent=2))
            outcomes.append(CaseOutcome(case, None, type(exc).__name__, str(exc)))
            continue
        assert isinstance(result, pd.DataFrame)  # nosec B101 - type-narrowing, not a security control
        result.to_csv(golden_dir / f"{case}.csv", index=False)
        stats = {"rows": len(result), "columns": list(result.columns)}
        (golden_dir / f"{case}.json").write_text(json.dumps(stats, indent=2))
        outcomes.append(CaseOutcome(case, len(result), None, None))

    test_file = repo_root / "tests" / "characterisation" / f"test_{name}.py"
    test_file.write_text(_TEST_TEMPLATE.format(name=name, n_cases=len(CASES)))
    return outcomes
