"""Human-readable code-graph report (CODE_GRAPH.md) with a Mermaid data-flow diagram."""

from __future__ import annotations

from collections import Counter

from teleguard.adapters.base import AnalysisResult
from teleguard.codegraph.merge import MergeReport
from teleguard.codegraph.model import LINEAGE_EDGES, CodeGraph, NodeType, Origin

_SHAPES = {NodeType.FIELD: ('(["', '"])'), NodeType.OUTPUT: ('[["', '"]]')}


def _mid(node_id: str) -> str:
    return "".join(c if c.isalnum() else "_" for c in node_id)


def mermaid(graph: CodeGraph) -> str:
    """Fields (rounded) and outputs (double boxes) joined by derives/produces edges."""
    lines = ["flowchart LR"]
    for node in graph.nodes:
        if node.type in _SHAPES:
            left, right = _SHAPES[node.type]
            marker = " *" if node.origin is Origin.RUNTIME else ""
            lines.append(f"    {_mid(node.id)}{left}{node.label}{marker}{right}")
    for edge in graph.edges:
        if edge.type in LINEAGE_EDGES:
            lines.append(f"    {_mid(edge.source)} --> {_mid(edge.target)}")
    return "\n".join(lines)


def report_markdown(name: str, result: AnalysisResult, merged: MergeReport | None) -> str:
    graph = result.graph
    counts = Counter(n.type.value for n in graph.nodes)
    stage_labels = " -> ".join(graph.node(s).label for s in result.stages) or "_no entry given_"
    checkpoints = "\n".join(f"| {c.name} | `{c.location}` | {c.attach.value} |"
                            for c in result.checkpoints)
    rows = "\n".join(
        f"| {i} | {f.kind.value} | {f.field or '-'} | {f.message} | "
        f"`{f.evidence.file}:{f.evidence.line}` |"
        for i, f in enumerate(result.findings, start=1))
    if merged:
        runtime = (f"- Fields in the code confirmed by the run: **{merged.confirmed_fields} of "
                   f"{merged.static_fields}** ({merged.field_agreement:.0%})\n"
                   f"- Field-to-field links confirmed: **{merged.confirmed_field_edges} of "
                   f"{merged.field_edges}** ({merged.edge_agreement:.0%})\n"
                   f"- Columns seen only at runtime (marked `*` in the diagram): "
                   f"{', '.join(merged.runtime_only_fields) or 'none'}\n"
                   f"- Fields in the code never seen running: "
                   f"{', '.join(merged.static_only_fields) or 'none'}")
    else:
        runtime = "_No runtime confirmation was run._"
    return f"""# Code graph: {name}

> Generated by `python -m teleguard.workflow`. Static analysis plus one confirmation run.
> **Findings are candidates, not facts.** A human confirms each one before it becomes a
> guarantee (see GUARANTEES.md).

## Summary
{", ".join(f"{v} {k}s" for k, v in sorted(counts.items()))} · {len(graph.edges)} edges ·
{len(result.findings)} findings

## Stages (from the entry function)
{stage_labels}

## Proposed checkpoints
| Checkpoint | Location | Attach |
|---|---|---|
{checkpoints}

## Runtime confirmation
{runtime}

## Data flow
```mermaid
{mermaid(graph)}
```

## Findings (candidate hidden rules)
| # | Kind | Field | What the code implies | Evidence |
|---|---|---|---|---|
{rows}
"""
