"""Characterisation tests for web_analytics. GENERATED by teleguard.workflow; do not edit.

The golden files pin what the pipeline does today, including behaviour that looks wrong.
"""

import io
import json
from pathlib import Path

import pandas as pd
import pytest

from teleguard.tracer import load_module

ROOT = Path(__file__).resolve().parents[2]
LEGACY = ROOT / "pipelines" / "web_analytics" / "legacy" / "run.py"
DATA = ROOT / "tests" / "data" / "web_analytics"
GOLDEN = Path(__file__).parent / "golden" / "web_analytics"
CASES = sorted(p.stem for p in GOLDEN.glob("*.json"))


def _run(case: str) -> pd.DataFrame:
    return load_module(LEGACY).run(DATA / case)


def _roundtrip(df: pd.DataFrame) -> pd.DataFrame:
    return pd.read_csv(io.StringIO(df.to_csv(index=False)), keep_default_na=False)


@pytest.mark.parametrize("case", CASES)
def test_case_matches_golden(case: str) -> None:
    expected = json.loads((GOLDEN / f"{case}.json").read_text())
    if "raises" in expected:
        with pytest.raises(Exception) as info:
            _run(case)
        assert type(info.value).__name__ == expected["raises"]
        assert str(info.value) == expected["message"]
        return
    result = _run(case)
    assert list(result.columns) == expected["columns"]
    assert len(result) == expected["rows"]
    golden = pd.read_csv(GOLDEN / f"{case}.csv", keep_default_na=False)
    pd.testing.assert_frame_equal(_roundtrip(result), golden, check_exact=False, rtol=1e-9)


def test_golden_covers_every_case() -> None:
    assert len(CASES) >= 7
